packages:
  - 'packages/*'
  - 'apps/*/client'
  - 'apps/*/api'

catalog:
  nuxt: 4.1.3
  vue: 3.5.13
  vuetify: 3.8.8
  vuetify-nuxt-module: 0.18.6
  "@mdi/font": 7.4.47
  "@vueuse/core": 13.3.0
  date-fns: 4.1.0
  mitt: 3.0.1
  validator: 13.15.26
  typescript: 5.9.3
  eslint: 9.28.0
  sass: 1.97.3
  "@nuxt/eslint": 1.4.1
  "@nuxt/eslint-config": 1.4.1
  "@types/validator": 13.15.10
  "@vitejs/plugin-vue": 6.0.3
  vite-plugin-vuetify: 2.1.1
  vue-tsc: 2.2.10
  v3-infinite-loading: 1.3.1
  express: 4.17.1
  cors: 2.8.5
  helmet: 5.0.1
  jsonwebtoken: 8.5.1
  winston: 3.2.1
  morgan: 1.9.1
  dotenv: 17.2.3
  bcryptjs: 2.4.3
  axios: 0.21.1
  nodemon: 2.0.2
  ts-node: 10.4.0
  lodash: 4.17.19
  uuid: 8.3.2
  reflect-metadata: 0.1.13
  "@mollie/api-client": 3.5.1
  config: 3.2.5
  ejs: 3.0.1

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - unrs-resolver
  - vue-demi
